language: go
os:
  - osx
script: make clean fetch-depends config cross-build-all-platform package-all-platform
go:
- 1.6
deploy:
  provider: releases
  skip_cleanup: false
  api_key:
    secure: Y34W9IfgIPA+/kkVfysNs6s/Zx5Rz2TK1Og1Tr9EGzDofadCs5e0Pjke1sU+VTcKIo8T4JGoDw5oUhC5CTsrq3iBa47hseFdQuERzLUKdEtaWIORTNcrJZJqitw/Fs50A6KPpN7Tvi6rOGD+pUi+lgYXbNvspyuVdHvW6HbcTvk=
  file: bin/*.tar.gz 
  file_glob: true
  on:
    repo: medcl/gopa
    tags: true
